---

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - airbnb

parser: '@typescript-eslint/parser'

parserOptions:
  "project": "tsconfig.json"
  "tsconfigRootDir": "."

plugins: ["@typescript-eslint"]

env:
  browser: true
  node: true
  es6: true
  es2017: true

settings:
  import/resolver:
    - node:
        paths: ['src']
    - webpack

rules:
  "import/extensions": [
     "error",
     "ignorePackages",
     {
       "js": "never",
       "jsx": "never",
       "ts": "never",
       "tsx": "never"
     }
  ]
  'no-underscore-dangle': [
    'error', {
      'allow': ["_id"]
    }
  ]
  'react/jsx-filename-extension': [2, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }]
  no-console: 0
