version: '3'
services:
  client:
    build: client
    image: enigmadie/client:v1
    container_name: blog-client
    restart: on-failure
    environment:
      - FRONT_ENV=production
    ports:
      - "8080:8080"
  server:
    build: server
    image: enigmadie/server:v1
    container_name: blog-server
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
